### ISSUE TITLE
Keep dependencies up-to-date

### ISSUE THREAD

**Issue by russellbanks** [Minionguyjpro/Inno-Setup-Action#5]
The dependencies in [`package.json`](https://github.com/Minionguyjpro/Inno-Setup-Action/blob/main/package.json) and [`package-lock.json`](https://github.com/Minionguyjpro/Inno-Setup-Action/blob/main/package-lock.json) haven't been updated since July 2023. Dependencies should be be kept updated.

Both [dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot) and [renovate](https://github.com/apps/renovate) are bots that automatically create pull requests that keep dependencies up-to-date.

**Comment by Minionguyjpro** [comment]
Just added the file needed for dependabot. Forgot to add it, but I already used it before for my other Node.js repository.

**Comment by Minionguyjpro** [comment]
@russellbanks Thanks for your suggestions! I've now managed to make it work so it runs the CJS code. If my script gets updated, GitHub Actions will make sure to compile it and make a commit and push if it got changed.
